
// This file has been generated by the GUI designer. Do not modify.
namespace Examples
{
	public partial class FlorenceDockingDemo
	{
		private global::Gtk.VBox vbox1;
		private global::Florence.GtkSharp.PlotWidget plotwidget1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Examples.FlorenceDockingDemo
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Examples.FlorenceDockingDemo";
			// Container child Examples.FlorenceDockingDemo.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.plotwidget1 = new global::Florence.GtkSharp.PlotWidget ();
			this.plotwidget1.Name = "plotwidget1";
			this.vbox1.Add (this.plotwidget1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.plotwidget1]));
			w1.Position = 1;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
